# Development Environment Configuration

app:
  name: friend
  replicas: 1
  port: 3001


# Development domain - change to your assigned domain
tlsSecret: root-tls
domain: ltu-m7011e-1.se
path: /api/friend

# Email for Let's Encrypt certificates
email: wilhgg-2@student.ltu.se

# Environment identifier
env: production

# Container image
image:
  repository: ghcr.io/melander00/m7011e_friend-service
  tag: "06130cc"

# Ingress configuration
ingress:
  # Use staging for testing to avoid rate limits
  certIssuer: letsencrypt-prod

redis:
  username: 
  password: 
  host: redis-service
  port: "6379"
  db: "2"

rabbit:
  username: "admin"
  password: "admin123"
  host: rabbitmq-service-api
  port: "5672"