apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: docker.io/melander00/ping
        ports:
        - containerPort: 3000
