apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  labels:
    app: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: docker.io/melander00/ping:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
        env:
          - name: PORT
            value: "3100"