apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.middlewares: default-ping-strip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: {{ .Values.path }}
        pathType: Prefix
        backend:
          service:
            name: ping
            port:
              number: 3100
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: ping-tls
