apiVersion: v1
kind: Service
metadata:
  name: ping
  labels:
    app: ping
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "8001"
  #   prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 3100
    targetPort: 3100
  selector:
    app: ping
