apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: leaderboard
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
          - name: REDIS_USERNAME
            value: "{{ .Values.redis.username }}"
          - name: REDIS_PASSWORD
            value: "{{ .Values.redis.password }}"
          - name: REDIS_HOST
            value: "{{ .Values.redis.host }}"
          - name: REDIS_PORT
            value: "{{ .Values.redis.port }}"
          - name: REDIS_DB
            value: "{{ .Values.redis.db }}"

          - name: RABBITMQ_USERNAME
            value: "{{ .Values.rabbit.username }}"
          - name: RABBITMQ_PASSWORD
            value: "{{ .Values.rabbit.password }}"
          - name: RABBITMQ_HOST
            value: "{{ .Values.rabbit.host }}"
          - name: RABBITMQ_PORT
            value: "{{ .Values.rabbit.port }}"

          - name: GAME_SERVER_IMAGE
            value: "{{ .Values.server.image }}:{{ .Values.server.serverTag }}"
          - name: GAME_SERVER_NAMESPACE
            value: "{{ .Values.server.namespace }}"
          - name: GAME_SERVER_DOMAIN
            value: "{{ .Values.server.domain }}"