apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: game-servers
  name: "pod-creator-{{ .Values.env }}"
rules:
  # Pods & Services
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "get", "list", "watch", "delete", "deletecollection"]
  # Ingresses
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "pod-creator-binding-{{ .Values.env }}"
  namespace: game-servers
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "pod-creator-{{ .Values.env }}"
  apiGroup: rbac.authorization.k8s.io
