{{- range .Values.hosts}}
{{- if not .skipService}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
spec:
  selector:
    app: {{ .appName }}
  ports:
  - port: {{ .servicePort }}
    targetPort: {{ .targetPort }}
  type: ClusterIP
---
{{- end}}
{{- end}}