apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      containers:
      - name: leaderboard
        image: docker.io/melander00/m7011e_leaderboard
        ports:
        - containerPort: 3005
        env:
          - name: PG_HOST
            value: postgres
          - name: PG_DATABASE
            value: postgres
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            value: admin
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password



