apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Value.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Value.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Value.app.name }}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 6379
        resources: {{ .Values.resources | toYaml }}