apiVersion: v1
kind: Service
metadata:
  name: {{ .Value.app.name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 6379
  selector:
    app: {{ .Value.app.name }}