apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-{{ .Values.image.tag }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    # argocd.argoproj.io/hook: PreSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
    # migration-image: "{{ .Values.image.tag }}"
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://postgres:5432/postgres"
            - name: FLYWAY_USER
              value: admin
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password