# Development Environment Configuration

app:
  name: leaderboard
  replicas: 1
  port: 3005

# Development domain - change to your assigned domain
domain: leaderboard-dev.ltu-m7011e-1.se

# Email for Let's Encrypt certificates
email: johan.kristiansson@ltu.se

# Environment identifier
environment: Development

# Container image
image:
  repository: ghcr.io/melander00/m7011e_leaderboard-service
  tag: "40a0e58"

# Ingress configuration
ingress:
  # Use staging for testing to avoid rate limits
  certIssuer: letsencrypt-staging


rabbit:
  username: "admin"
  password: "admin123"
  host: rabbitmq-service-api.rabbitmq.svc.cluster.local
  port: "5672"