# Development Environment Configuration

app:
  name: leaderboard
  replicas: 1
  port: 3005

# Development domain - change to your assigned domain
tlsSecret: root-tls
domain: dev.ltu-m7011e-1.se
path: /api/leaderboard

# Email for Let's Encrypt certificates
email: irmpal-1@student.ltu.se

# Environment identifier
env: development

# Container image
image:
  repository: ghcr.io/melander00/m7011e_leaderboard-service
  tag: "9749d8c"

# Ingress configuration
ingress:
  # Use staging for testing to avoid rate limits
  certIssuer: letsencrypt-staging


rabbit:
  username: "admin"
  password: "admin123"
  host: rabbitmq-service-api
  port: "5672"