app:
  name: leaderboard
  replicas: 1
  port: 3005

# Development domain - change to your assigned domain
domain: leaderboard.ltu-m7011e-1.se

# Email for Let's Encrypt certificates
email: johan.kristiansson@ltu.se

# Environment identifier
environment: Production

# Container image
image:
  repository: ghcr.io/melander00/m7011e_leaderboard
  tag: 0f0cb39